import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { Footer } from "./components/footer";
import { Header } from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jobby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased px-2 h-dvh`}>
        
        <div className="flex flex-row border-4 border-purple-500 w-full h-full grid  grid-cols-5 grid-rows-2 gap-2">
              <div className="row-span-2 row-start-1 col-span-1">
                <Navigation />
              </div>
              
              <div className="row-span-1 row-start-1 col-span-4">
                <Header />
              </div>
              <div className="row-span-1 row-start-2 col-span-4">
                {children}
              </div>
  
{/*            <div className="basis-2/3 border-4 border-blue-500 rounded-3xl bg-green-200 grid items-center justify-items-center">
              Click a job for description
            </div>*/}
        </div>
               <div className="absolute bottom-0 w-full col-span-5">
                <Footer />
              </div>  

      </body>
    </html>
  );
}
