import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { Footer } from "./components/footer";
import { Header } from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jobby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white">
        <header className="border-b">
          <div className="container mx-auto px-4 py-3 flex justify-between items-center">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 border rounded flex items-center justify-center text-green-400 text-2xl border-4 font-bold border-green-400">
                J
              </div>
              <h1 className="text-2xl font-bold text-green-400">Jobby</h1>
            </div>
            <button className="px-4 py-2 border rounded bg-green-400 hover:bg-green-200 text-white font-bold">Log In</button>
          </div>
        </header>
        <main className="container mx-auto px-4 py-6">
          {children}
        </main>
        <div className="absolute bottom-0 w-full col-span-5">
          <Footer />
        </div>  
      </body>
    </html>
  );
}
